apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: k8s-demo
        image: rakmodi/sample-app:latest 
        ports:
        - name: nodejs-port
          containerPort: 80

